### ISSUE TITLE
Stupid question: Isn't only a small part of the test set being used?

### ISSUE THREAD

**Issue by tuhe** [FrancescoSaverioZuppichini/Tensorflow-Dataset-Tutorial#1]
Hi!

I have a question regarding your dataset example. It seems to me that only a only 16 of the 20 test examples are used when computing the test error:

`sess.run(iter.initializer, feed_dict={ x: test_data[0], y: test_data[1]})`

(from https://github.com/FrancescoSaverioZuppichini/Tensorflow-Dataset-Tutorial/blob/master/dataset_tutorial.ipynb )

because the iterator is using a BATCH_SIZE of 16. Obviously one could set BATCH_SIZE=#elements in the test set, however this seems inelegant. I wonder if this is the case and if so if you have a fix?

UPDATE: 
A workaround I am using is to set BATCH_SIZE equal to a placeholder node and then let it be equal to the size of the test set when x,y are assigned using feed_dict:

sess.run(iter.initializer, feed_dict ={x : x_test, y : y_test, BATCH_SIZE_PLACEHOLDER : N_train})

 -- this is not a very elegant solution obviously but it seem to work. If you got any ideas for a more elegant solution (this issue seems to be something *everyone* encounters) I would be very interested in hearing your thoughts -- this is my first day with tensorflow and I think blog posts such as yours are of great utility for those of us just starting out.

Regards!

**Comment by FrancescoSaverioZuppichini** [comment]
Hi @tuhe,

Yes you are totally correct! You should use a placeholder to store the batch_size and change it when you need. As far as I know, there is no other solution, you could, instead, create two datasets and switch the iterator between them. I will update the blog post and the code as soon as possible.

All the bests,

Francesco Saverio
