### ISSUE TITLE
TypeError: Can't instantiate abstract class Dataset with abstract methods _as_variant_tensor, output_classes, output_shapes, output_types

### ISSUE THREAD

**Issue by upwindflys** [FrancescoSaverioZuppichini/Tensorflow-Dataset-Tutorial#2]
when i try the code From generator,there is a TypeError,do anyone knows about it?

**Comment by upwindflys** [comment]
problem solved,tf.data.Dataset.from_generator

**Comment by FrancescoSaverioZuppichini** [comment]
What was the problem?

**Comment by hamid95reza** [comment]
Hi

**Comment by Yousef11111** [comment]
Possibly using a depreacated code like tf.data.Dataset().from_generator(). So deleting () will solve the problem.

**Comment by FrancescoSaverioZuppichini** [comment]
I won't support this code anymore, I switched to PyTorch and my life is better

**Comment by Yousef11111** [comment]
Really, Let me check it by then, maybe I did the same job.

**Comment by FrancescoSaverioZuppichini** [comment]
Sorry, I don't understand
